# Generated by Django 4.2.25 on 2025-10-26 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adsoyad', models.CharField(max_length=255, verbose_name='Ad Soyad')),
                ('kullaniciadi', models.CharField(max_length=255, unique=True, verbose_name='Kullanıcı Adı')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta')),
                ('yonetici', models.BooleanField(default=False, verbose_name='Yönetici')),
                ('gg', models.BooleanField(default=False, verbose_name='Gizli Kullanıcı')),
                ('girisizni', models.BooleanField(default=False, verbose_name='Giriş İzni Yok')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Personel')),
                ('kalanizin', models.IntegerField(default=0, verbose_name='Kalan İzin (Gün)')),
            ],
            options={
                'verbose_name': 'Personel',
                'verbose_name_plural': 'Personeller',
                'db_table': 'sofor',
            },
        ),
        migrations.CreateModel(
            name='Arac',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plaka', models.CharField(max_length=100, verbose_name='Plaka')),
                ('kategori', models.CharField(choices=[('binek', 'Binek'), ('minubus', 'Minibüs'), ('otobus', 'Otobüs'), ('kamyonet', 'Kamyonet'), ('kamyon', 'Kamyon')], max_length=20, verbose_name='Kategori')),
                ('marka', models.CharField(max_length=100, verbose_name='Marka')),
                ('zimmet', models.CharField(blank=True, max_length=250, verbose_name='Zimmet')),
                ('yolcusayisi', models.CharField(blank=True, max_length=10, verbose_name='Yolcu Sayısı')),
                ('muayene', models.DateTimeField(blank=True, null=True, verbose_name='Muayene Tarihi')),
                ('muayenedurum', models.IntegerField(default=0, verbose_name='Muayene Durumu')),
                ('sigorta', models.DateTimeField(blank=True, null=True, verbose_name='Sigorta Tarihi')),
                ('egzoz', models.DateTimeField(blank=True, null=True, verbose_name='Egzoz Tarihi')),
                ('gizle', models.BooleanField(default=False, verbose_name='Gizle')),
                ('takip', models.BooleanField(default=False, verbose_name='Takip')),
                ('arsiv', models.BooleanField(default=False, verbose_name='Arşiv')),
            ],
            options={
                'verbose_name': 'Araç',
                'verbose_name_plural': 'Araçlar',
                'db_table': 'arac',
            },
        ),
        migrations.CreateModel(
            name='Mesai',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bstarih', models.DateTimeField(verbose_name='Başlangıç Tarihi')),
                ('bttarih', models.DateTimeField(verbose_name='Bitiş Tarihi')),
                ('mesai', models.CharField(max_length=255, verbose_name='Mesai Süresi (Saat)')),
                ('gorev', models.TextField(verbose_name='Görev Açıklaması')),
                ('pazargunu', models.BooleanField(default=False, verbose_name='Pazar Günü')),
                ('durum', models.IntegerField(blank=True, null=True, verbose_name='Durum')),
                ('arac', models.ForeignKey(blank=True, db_column='aracid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.arac', verbose_name='Araç')),
                ('sofor', models.ForeignKey(db_column='soforid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Personel')),
            ],
            options={
                'verbose_name': 'Mesai',
                'verbose_name_plural': 'Mesailer',
                'db_table': 'mesai',
                'ordering': ['-bstarih'],
            },
        ),
        migrations.CreateModel(
            name='Malzeme',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bstarih', models.DateTimeField(verbose_name='Tarih')),
                ('aciklama', models.TextField(verbose_name='Malzeme Açıklaması')),
                ('sofor', models.ForeignKey(db_column='soforid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Personel')),
            ],
            options={
                'verbose_name': 'Malzeme',
                'verbose_name_plural': 'Malzemeler',
                'db_table': 'malzeme',
                'ordering': ['-bstarih'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('islem', models.TextField(verbose_name='İşlem')),
                ('tarih', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('ip', models.CharField(blank=True, max_length=255, null=True, verbose_name='IP Adresi')),
                ('sofor', models.ForeignKey(db_column='soforid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Personel')),
            ],
            options={
                'verbose_name': 'Log Kaydı',
                'verbose_name_plural': 'Log Kayıtları',
                'db_table': 'log',
                'ordering': ['-tarih'],
            },
        ),
        migrations.CreateModel(
            name='Izin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bstarih', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('bttarih', models.DateField(verbose_name='Bitiş Tarihi')),
                ('izin', models.CharField(choices=[('1', 'Yıllık İzin'), ('2', 'Mazeret İzni'), ('3', 'Fazla Mesai İzni'), ('4', 'Saatlik İzin')], max_length=10, verbose_name='İzin Türü')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('gun', models.IntegerField(default=0, verbose_name='Gün')),
                ('saat', models.IntegerField(default=0, verbose_name='Saat')),
                ('sofor', models.ForeignKey(db_column='soforid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Personel')),
            ],
            options={
                'verbose_name': 'İzin',
                'verbose_name_plural': 'İzinler',
                'db_table': 'izin',
                'ordering': ['-bstarih'],
            },
        ),
        migrations.CreateModel(
            name='GorevYeri',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ad', models.CharField(max_length=255, verbose_name='Görev Yeri Adı')),
            ],
            options={
                'verbose_name': 'Görev Yeri',
                'verbose_name_plural': 'Görev Yerleri',
                'db_table': 'yurt',
                'indexes': [models.Index(fields=['ad'], name='yurt_ad_0d880d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Gorevlendirme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bstarih', models.DateTimeField(verbose_name='Başlangıç Tarihi')),
                ('bttarih', models.DateTimeField(verbose_name='Bitiş Tarihi')),
                ('gorev', models.TextField(verbose_name='Görev Açıklaması')),
                ('arac', models.ForeignKey(blank=True, db_column='aracid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.arac', verbose_name='Araç')),
                ('sofor', models.ForeignKey(db_column='soforid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Personel')),
            ],
            options={
                'verbose_name': 'Görevlendirme',
                'verbose_name_plural': 'Görevlendirmeler',
                'db_table': 'gorevlendirmeler',
                'ordering': ['-bstarih'],
            },
        ),
        migrations.CreateModel(
            name='Gorev',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('varisyeri', models.CharField(default='Düzenlenecek', max_length=250, verbose_name='Varış Yeri')),
                ('bstarih', models.DateTimeField(verbose_name='Başlangıç Tarihi')),
                ('bttarih', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('yetkili', models.CharField(max_length=250, verbose_name='Yetkili')),
                ('ilolur', models.CharField(blank=True, max_length=50, null=True, verbose_name='İl Olur')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('gizle', models.BooleanField(default=False, verbose_name='Gizle')),
                ('durum', models.IntegerField(blank=True, null=True, verbose_name='Durum')),
                ('aktarildi', models.IntegerField(default=0, verbose_name='Aktarıldı')),
                ('arac', models.ForeignKey(blank=True, db_column='aracid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.arac', verbose_name='Araç')),
                ('sofor', models.ForeignKey(db_column='soforid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Personel')),
                ('yurt', models.ForeignKey(db_column='yurtid', on_delete=django.db.models.deletion.CASCADE, to='core.gorevyeri', verbose_name='Görev Yeri')),
            ],
            options={
                'verbose_name': 'Görev',
                'verbose_name_plural': 'Görevler',
                'db_table': 'gorev',
                'ordering': ['-bstarih'],
            },
        ),
        migrations.AddIndex(
            model_name='arac',
            index=models.Index(fields=['plaka'], name='arac_plaka_ddb111_idx'),
        ),
        migrations.AddIndex(
            model_name='arac',
            index=models.Index(fields=['kategori'], name='arac_kategor_ddc0ca_idx'),
        ),
        migrations.AddIndex(
            model_name='arac',
            index=models.Index(fields=['arsiv'], name='arac_arsiv_20a50f_idx'),
        ),
        migrations.AddField(
            model_name='personel',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='personel',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='mesai',
            index=models.Index(fields=['sofor'], name='mesai_soforid_7d90a2_idx'),
        ),
        migrations.AddIndex(
            model_name='mesai',
            index=models.Index(fields=['bstarih'], name='mesai_bstarih_38c358_idx'),
        ),
        migrations.AddIndex(
            model_name='malzeme',
            index=models.Index(fields=['sofor'], name='malzeme_soforid_921dce_idx'),
        ),
        migrations.AddIndex(
            model_name='malzeme',
            index=models.Index(fields=['bstarih'], name='malzeme_bstarih_8e333e_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['sofor'], name='log_soforid_7576fa_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['tarih'], name='log_tarih_499e75_idx'),
        ),
        migrations.AddIndex(
            model_name='izin',
            index=models.Index(fields=['sofor'], name='izin_soforid_3337ca_idx'),
        ),
        migrations.AddIndex(
            model_name='izin',
            index=models.Index(fields=['bstarih'], name='izin_bstarih_84a6ca_idx'),
        ),
        migrations.AddIndex(
            model_name='gorevlendirme',
            index=models.Index(fields=['sofor'], name='gorevlendir_soforid_003404_idx'),
        ),
        migrations.AddIndex(
            model_name='gorevlendirme',
            index=models.Index(fields=['bstarih'], name='gorevlendir_bstarih_a831f4_idx'),
        ),
        migrations.AddIndex(
            model_name='gorev',
            index=models.Index(fields=['bstarih'], name='gorev_bstarih_6f861b_idx'),
        ),
        migrations.AddIndex(
            model_name='gorev',
            index=models.Index(fields=['bttarih'], name='gorev_bttarih_820079_idx'),
        ),
        migrations.AddIndex(
            model_name='gorev',
            index=models.Index(fields=['durum'], name='gorev_durum_e85400_idx'),
        ),
        migrations.AddIndex(
            model_name='gorev',
            index=models.Index(fields=['gizle'], name='gorev_gizle_ee2567_idx'),
        ),
        migrations.AddIndex(
            model_name='personel',
            index=models.Index(fields=['kullaniciadi'], name='sofor_kullani_cb8fe3_idx'),
        ),
    ]
